SELECT *
FROM RAW_DRUG_SAFETY;
SELECT DISTINCT drugname
FROM RAW_DRUG_SAFETY;
SELECT COUNT(DISTINCT drugname) AS TOTAL_DRUGS
FROM RAW_DRUG_SAFETY;
SELECT *
FROM RAW_DRUG_SAFETY
WHERE age IS NULL
   OR sex IS NULL
   OR pt IS NULL;
   SELECT COUNT(*) AS MISSING_AGE
FROM RAW_DRUG_SAFETY
WHERE age IS NULL;
SELECT sex,
       COUNT(*) AS TOTAL_PATIENTS
FROM RAW_DRUG_SAFETY
GROUP BY sex;
SELECT pt,
       COUNT(*) AS AE_COUNT
FROM RAW_DRUG_SAFETY
GROUP BY pt
ORDER BY AE_COUNT DESC;
SELECT drugname,
       COUNT(*) AS TOTAL_AE
FROM RAW_DRUG_SAFETY
GROUP BY drugname
ORDER BY TOTAL_AE DESC;
SELECT age,
       COUNT(*) AS TOTAL_CASES
FROM RAW_DRUG_SAFETY
GROUP BY age
ORDER BY TOTAL_CASES DESC;
SELECT primaryid,
       COUNT(*) AS DUPLICATE_COUNT
FROM RAW_DRUG_SAFETY
GROUP BY primaryid
HAVING COUNT(*) > 1;
SELECT role_cod,
       COUNT(*) AS TOTAL_RECORDS
FROM RAW_DRUG_SAFETY
GROUP BY role_cod;
SELECT *
FROM RAW_DRUG_SAFETY
WHERE pt LIKE '%death%'
   OR pt LIKE '%failure%'
   OR pt LIKE '%toxicity%';
--SAFETY RECONCILIATION WORKFLOWS--
CREATE TABLE SAFETY_REVIEW AS
SELECT
    primaryid,
    drugname,
    pt,
    age,
    sex,

    CASE
        WHEN age >= 65 THEN 'HIGH RISK'
        ELSE 'STANDARD'
    END AS RISK_CATEGORY,

    CASE
        WHEN pt LIKE '%death%'
          OR pt LIKE '%failure%'
          OR pt LIKE '%toxicity%'
        THEN 'SERIOUS'

        ELSE 'NON-SERIOUS'
    END AS SERIOUSNESS

FROM RAW_DRUG_SAFETY;
SELECT *
FROM SAFETY_REVIEW;
SELECT SERIOUSNESS,
       COUNT(*) AS TOTAL_CASES
FROM SAFETY_REVIEW
GROUP BY SERIOUSNESS;
SELECT *
FROM SAFETY_REVIEW
WHERE RISK_CATEGORY = 'HIGH RISK';
CREATE TABLE QUERY_MANAGEMENT AS
SELECT
    primaryid,
    drugname,
    pt,

    CASE
        WHEN age IS NULL THEN 'MISSING AGE'

        WHEN sex IS NULL THEN 'MISSING SEX'

        ELSE 'NO ISSUE'
    END AS QUERY_STATUS

FROM RAW_DRUG_SAFETY;
SELECT *
FROM QUERY_MANAGEMENT;
SELECT QUERY_STATUS,
       COUNT(*) AS TOTAL_RECORDS
FROM QUERY_MANAGEMENT
GROUP BY QUERY_STATUS;
SELECT drugname,
       COUNT(*) AS TOTAL_EVENTS
FROM SAFETY_REVIEW
GROUP BY drugname
HAVING COUNT(*) > 10
ORDER BY TOTAL_EVENTS DESC;
SELECT *
FROM SAFETY_REVIEW
WHERE RISK_CATEGORY = 'HIGH RISK'
  AND SERIOUSNESS = 'SERIOUS';
  SELECT COUNT(*) AS TOTAL_SAFETY_CASES
FROM SAFETY_REVIEW;
SELECT SERIOUSNESS,
       COUNT(*) AS TOTAL_CASES
FROM SAFETY_REVIEW
GROUP BY SERIOUSNESS;
SELECT RISK_CATEGORY,
       COUNT(*) AS TOTAL_PATIENTS
FROM SAFETY_REVIEW
GROUP BY RISK_CATEGORY;
SELECT pt,
       COUNT(*) AS TOTAL_EVENTS
FROM SAFETY_REVIEW
GROUP BY pt
ORDER BY TOTAL_EVENTS DESC;
SELECT drugname,
       COUNT(*) AS TOTAL_EVENTS
FROM SAFETY_REVIEW
GROUP BY drugname
ORDER BY TOTAL_EVENTS DESC;
SELECT drugname,
       COUNT(*) AS TOTAL_EVENTS
FROM SAFETY_REVIEW
GROUP BY drugname
ORDER BY TOTAL_EVENTS DESC;
SELECT QUERY_STATUS,
       COUNT(*) AS TOTAL_ISSUES
FROM QUERY_MANAGEMENT
GROUP BY QUERY_STATUS;
CREATE VIEW FINAL_SAFETY_RECONCILIATION AS

SELECT
    primaryid,
    drugname,
    pt,
    age,
    sex,

    CASE
        WHEN age IS NULL
          OR sex IS NULL
        THEN 'QUERY RAISED'

        ELSE 'VALIDATED'
    END AS DATA_STATUS,

    CASE
        WHEN pt LIKE '%death%'
          OR pt LIKE '%failure%'
          OR pt LIKE '%toxicity%'
        THEN 'SERIOUS AE'

        ELSE 'NON-SERIOUS AE'
    END AS SAFETY_CLASSIFICATION

FROM RAW_DRUG_SAFETY;
SELECT *
FROM FINAL_SAFETY_RECONCILIATION;
SELECT DATA_STATUS,
       SAFETY_CLASSIFICATION,
       COUNT(*) AS TOTAL_RECORDS
FROM FINAL_SAFETY_RECONCILIATION
GROUP BY DATA_STATUS, SAFETY_CLASSIFICATION
ORDER BY TOTAL_RECORDS DESC;
SELECT
    primaryid,
    drugname,
    pt,

    CASE
        WHEN pt LIKE '%death%'
          OR pt LIKE '%failure%'
          OR pt LIKE '%toxicity%'
        THEN 'HIGH PRIORITY'

        ELSE 'STANDARD PRIORITY'
    END AS CASE_PRIORITY

FROM RAW_DRUG_SAFETY;
--dashboad summary--
SELECT
    COUNT(*) AS TOTAL_CASES,

    SUM(
        CASE
            WHEN age IS NULL OR sex IS NULL
            THEN 1
            ELSE 0
        END
    ) AS TOTAL_DATA_QUERIES,

    SUM(
        CASE
            WHEN pt LIKE '%death%'
              OR pt LIKE '%failure%'
              OR pt LIKE '%toxicity%'
            THEN 1
            ELSE 0
        END
    ) AS SERIOUS_AE_CASES

FROM RAW_DRUG_SAFETY;
SELECT COUNT(*) AS TOTAL_RECORDS
FROM RAW_DRUG_SAFETY;